name: publish-modules-plugin

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to be used as release name and image tagging

permissions:
  contents: write

jobs:
  publish-module-plugin-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Update version
        working-directory: plugins/cyclops-modules
        run: |
          jq '.version = "0.2.3-rc.1"' package.json > tmp.json && mv tmp.json package.json
      - name: Build types
        run: |
          yarn tsc
      - name: Build and publish modules plugin
        working-directory: plugins/cyclops-modules
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_MODULES_PLUGIN_TOKEN }}
        run: |
          yarn build
          npm publish --access public
      - name: Commit new version
        run: |
          TAG=${{ github.event.inputs.version }}
          INSTALL_YAML=$GITHUB_WORKSPACE/install/cyclops-install.yaml

          sed -i 's/cyclopsui\/cyclops-ctrl\:.*/cyclopsui\/cyclops-ctrl\:'$TAG'/' $INSTALL_YAML
          sed -i 's/cyclopsui\/cyclops-ui\:.*/cyclopsui\/cyclops-ui\:'$TAG'/' $INSTALL_YAML

          # update file
          git fetch origin publish-plugin-action
          git checkout publish-plugin-action
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git status
          git add plugins/cyclops-modules/package.json
          git commit -m '⚙️ update cyclops modules plugin version'
          git push origin HEAD:publish-plugin-action
